project_name: 'lacmus_competition'

data_root: '/home/cds-k/Desktop/lacmus/data_lacmus/TrainingData'
test_root: '/home/cds-k/Desktop/lacmus/data_lacmus/EmptyPart'
checkpoints_dir: './checkpoints'
submissions_dir: './submissions'

split:
  train: 'train_non_empty' #train
  val: 'valtest' #valtest test

batch_size: 1
num_epochs: 21
device: 'cuda:0'
score_threshold: 0.2
submission_filename: 'bs_1_ep_21_thr_0_2'
model_filename: 'bs_1_ep_21_thr_0_2'

model:
  pretrained: false
  pretrained_backbone: true
  min_size: 900
  max_size: 1200
  trainable_backbone_layers: 0

optimizer:
  lr: 0.01
  momentum: 0.9
  weight_decay: 0.0005

lr_scheduler:
  step_size: 5
  gamma: 0.1


