project_name: 'lacmus_competition'

data_root: '/home/cds-k/Desktop/lacmus/data_lacmus/TrainingData'
test_root: '/home/cds-k/Desktop/lacmus/data_lacmus/EmptyPart'
checkpoints_dir: './checkpoints'
submissions_dir: './submissions'

split:
  train: 'train_non_empty' #train
  val: 'valtest' #valtest test

batch_size: 1
num_epochs: 5
device: 'cuda:0'
score_threshold: 0.05
submission_filename: 'resize'
model_filename: 'resize'

transforms:
  resize:
    h: 1500
    w: 2000

model:
  pretrained: false
  pretrained_backbone: true
  min_size: 2250
  max_size: 5472
  trainable_backbone_layers: 0

optimizer:
  lr: 0.001
  momentum: 0.9
  weight_decay: 0.0005

lr_scheduler:
  step_size: 3
  gamma: 0.1


