project_name: 'lacmus_competition'

data_root: '/home/adeshkin/Desktop/data_lacmus/TrainingData'
test_root: '/home/adeshkin/Desktop/data_lacmus/EmptyPart'
checkpoints_dir: './checkpoints'
submissions_dir: './submissions'

split:
  train: 'train_non_empty' #train
  val: 'valtest' #valtest test

batch_size: 1
num_epochs: 15
device: 'cuda:0'
score_threshold: 0.05
submission_filename: 'no_resize'

transforms:
  resize:
    h: 1500
    w: 2000

model:
  filename: ''
  pretrained: false
  pretrained_backbone: true
  min_size:
  max_size:
  trainable_backbone_layers: 0

optimizer:
  lr: 0.01
  momentum: 0.9
  weight_decay: 0.0005

lr_scheduler:
  step_size: 3
  gamma: 0.1


