project_name: 'lacmus_competition'
data_root: '/home/cds-k/Desktop/lacmus/data_lacmus/TrainingData'
train_mode: 'train_non_empty' #train
val_mode: 'valtest' #valtest test
target_h: 900
target_w: 1200
batch_size: 4
lr: 0.001
momentum: 0.9
weight_decay: 0.0005
step_size: 3
gamma: 0.1
num_epochs: 100
checkpoints_dir: './checkpoints'