project_name: 'lacmus_competition'
data_root: '/home/adeshkin/Desktop/data_lacmus/TrainingData'
test_root: '/home/adeshkin/Desktop/data_lacmus/EmptyPart'
train_mode: 'train_non_empty' #train
val_mode: 'valtest' #valtest test
target_h: 1500
target_w: 2000
batch_size: 4
lr: 0.01
momentum: 0.9
weight_decay: 0.0005
step_size: 3
gamma: 0.1
submission_filename: 'no_resize'
model: ''
num_epochs: 10
checkpoints_dir: './checkpoints'
submissions_dir: './submissions'